# productive routes
blank:
  path: /
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showIndex }

home:
  path: /home
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showIndex }

downloadAndroidApp:
  path: /download/app/android
  defaults: { _controller: escapeZombieHorde\Controller\AppController::checkIfAndroidAppIsExistent }

showDocumentation:
  path: /documentation
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showDocumentation }


createNewPlayer:
  path: /api/playerNew
  defaults: { _controller: escapeZombieHorde\Controller\AppController::createNewPlayer }
