# productive routes
blank:
  path: /
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showIndex }

home:
  path: /home
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showIndex }

downloadAndroidApp:
  path: /download/app/android
  defaults: { _controller: escapeZombieHorde\Controller\AppController::checkIfAndroidAppIsExistent }

showDocumentation:
  path: /documentation
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showDocumentation }


createNewPlayer:
  path: /api/player/create/new
  defaults: { _controller: escapeZombieHorde\Controller\Api::createNewPlayer }

getCurrentPlayerInfo:
  path: /api/get/session/player
  defaults: { _controller: escapeZombieHorde\Controller\Api::getSessionPlayer }

deleteSessionPlayer:
  path: /api/delete/session/player
  defaults: { _controller: escapeZombieHorde\Controller\Api::deleteSessionPlayer }