# productive routes
blank:
  path: /
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showIndex }

home:
  path: /home
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showIndex }

downloadAndroidApp:
  path: /download/app/android
  defaults: { _controller: escapeZombieHorde\Controller\AppController::checkIfAndroidAppIsExistent }

showDocumentation:
  path: /documentation
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showDocumentation }


createNewPlayer:
  path: /api/create/player
  defaults: { _controller: escapeZombieHorde\Controller\Api::createNewPlayer }

getCurrentPlayerInfo:
  path: /api/get/player
  defaults: { _controller: escapeZombieHorde\Controller\Api::getSessionPlayer }

getActivePlayersInfo:
  path: /api/get/players
  defaults: { _controller: escapeZombieHorde\Controller\Api::getActivePlayers }

deleteSessionPlayer:
  path: /api/delete/player
  defaults: { _controller: escapeZombieHorde\Controller\Api::deleteSessionPlayer }

deleteAllZombies:
  path: /api/delete/zombies
  defaults: { _controller: escapeZombieHorde\Controller\Api::deleteAllZombies }

deleteAll:
  path: /api/delete/all
  defaults: { _controller: escapeZombieHorde\Controller\Api::deleteAll }

startGame:
  path: /api/game/start
  defaults: { _controller: escapeZombieHorde\Controller\Api::startGame }

updatePlayerPosition:
  path: /api/update/player/position
  defaults: { _controller: escapeZombieHorde\Controller\Api::updatePlayerPosition }

updateZombiePosition:
  path: /api/update/zombie/position
  defaults: { _controller: escapeZombieHorde\Controller\Api::updateZombiePosition }