# dev routes for local development
blank:
  path: /escapeZombieHorde/
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showIndex }

home:
  path: /escapeZombieHorde/home
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showIndex }

downloadAndroidApp:
  path: /escapeZombieHorde/download/app/android
  defaults: { _controller: escapeZombieHorde\Controller\AppController::checkIfAndroidAppIsExistent }

showDocumentation:
  path: /escapeZombieHorde/documentation
  defaults: { _controller: escapeZombieHorde\Controller\AppController::showDocumentation }


createNewPlayer:
  path: /escapeZombieHorde/api/create/player
  defaults: { _controller: escapeZombieHorde\Controller\Api::createNewPlayer }

getCurrentPlayerInfo:
  path: /escapeZombieHorde/api/get/player
  defaults: { _controller: escapeZombieHorde\Controller\Api::getSessionPlayer }

getActivePlayersInfo:
  path: /escapeZombieHorde/api/get/players
  defaults: { _controller: escapeZombieHorde\Controller\Api::getActivePlayers }

deleteSessionPlayer:
  path: /escapeZombieHorde/api/delete/player
  defaults: { _controller: escapeZombieHorde\Controller\Api::deleteSessionPlayer }

startGame:
  path: /escapeZombieHorde/api/game/start
  defaults: { _controller: escapeZombieHorde\Controller\Api::startGame }